spring:
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"

logging:
  level:
    org:
      springframework: DEBUG

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com
    endpoint:
      models: /v1/models
      completions: /v1/chat/completions
